server:
  rootPath: /api/*
  applicationConnectors:
  - type: http
    port: 8090
  adminConnectors:
  - type: http
    port: 18090
assets:
  overrides:
    /: ./app
    /styles/: ./.tmp/styles

database:
  driverClass: com.microsoft.sqlserver.jdbc.SQLServerDriver
  user: kpsys
  password: kpsys
  url: jdbc:sqlserver://db.kpsys.com:1433;databaseName=kpsys
  properties:
    charSet: UTF-8
    hibernate.dialect: org.hibernate.dialect.SQLServer2012Dialect
  maxWaitForConnection: 1s
  minSize: 8
  maxSize: 32
  checkConnectionWhileIdle: true
  evictionInterval: 10s
  minIdleTime: 1 minute

logging:
  level: INFO
  loggers:
    io.dropwizard.jersey.jackson: DEBUG
    com.kpsys: DEBUG
    org.hibernate.SQL:
      level: DEBUG
